<body>
<?php //echo $this->partial('partials/feedback.phtml'); ?>
<div id="wrapper">

	<?php 
            echo $this->partial('partials/header.phtml', 
                          array( 'lang' => $this->lang , 
                                 'constants' => $this->constants,
                                 'uri' => $this->uri)); 
	?>
	<div id="content">
		<a href="/<?php echo ($this->lang == 'ua' ? '' : $this->lang . '/'); ?>" id="back"><?php echo $this->constants['back_to_home_' . $this->lang][0]; ?></a> 
		<br/>
		<br/>
		<div id="portfolioHeader"><?php echo $this->constants['portfolio_title_' . $this->lang][0]; ?></div>
		<br/>
		<div id="worksNavigation">
			<span><?php echo $this->constants['what_works_show_' . $this->lang][0]; ?>:</span> 
			<a href="/<?php echo ($this->lang == 'ua' ? '' : $this->lang . '/'); ?>portfolio/" class="pasiveWorks"><?php echo $this->constants['all_works_' . $this->lang][0]; ?></a>
			<a href="/<?php echo ($this->lang == 'ua' ? '' : $this->lang . '/'); ?>portfolio/complex-works/" class="activeWorks"><?php echo $this->constants['complex_works_' . $this->lang][0]; ?></a>
		</div>
		<br/><br/>
		<div id="slogan">
			<?php echo $this->constants['portfolio_text_' . $this->lang][0]; ?>
		</div>
		<table>
			<tr>
				<td>
					<div id="posts">
						<?php foreach($this->posts as $post) :?>
						<div class="post">
							<div class="date">
								<span class="day"><?php echo (int)$post['date']['day'];?></span><br/>
								<span class="month"><?php echo $post['date']['month'];?> <?php echo $post['date']['year'];?></span>
							</div>
							<div class="countComments"><?php echo $post['comment_count'];?></div>
							<div class="title">
								<a href="/<?php echo ($this->lang == 'ua' ? '' : $this->lang . '/'); ?>blog/post/<?php echo $post['uri'];?>"><?php echo $post['title_' . $this->lang];?></a>
							</div>
							<div class="postInfo"><?php echo $this->constants['author_' . $this->lang][0]; ?>: 
									<?php 
										$authors = '';
										foreach($post['authors'] as $author){
											$authors .= $author['name_' . $this->lang] . ', ';
										}
									?>
									<span class="author">
										<?php echo substr($authors, 0, strlen($authors) - 2) . ' '; ?>
									</span> 
									<?php 
										$labels = '';
										foreach($post['labels'] as $label){
											$labels .= $label['name_' . $this->lang] . ', ';
										}
									?> 
									<span class="labels">
										<?php echo substr($labels, 0, strlen($labels) - 2) . ' '; ?>
									</span>
							</div>
							<a href="/<?php echo ($this->lang == 'ua' ? '' : $this->lang . '/'); ?>blog/post/<?php echo $post['uri'];?>"><img src="/img/posts/<?php echo $post['uri']?>/<?php echo $post['title_img']?>" class="postImg"/></a>
							<div class="description">
								<?php echo $post['desc_' . $this->lang];?>
							</div>
							<a href="/<?php echo ($this->lang == 'ua' ? '' : $this->lang . '/'); ?>blog/post/<?php echo $post['uri'];?>" class="details"><?php echo $this->constants['read_' . $this->lang][0]; ?></a><br/>
						</div>
						<br/>
						<?php endforeach; ?>
					</div>
					<div id="rightMenu" style="padding-top: 50px;">
						<div id="rightMenuHeader"><?php echo $this->constants['labs_' . $this->lang][0]; ?>:</div>
						<br/>
						<ul class="labMenu">
							<?php foreach($this->labChapters as $chapter):?>
								<li class="<?php echo strtolower($chapter['lab']); ?>"><a href="/<?php echo ($this->lang == 'ua' ? '' : $this->lang . '/'); ?>portfolio/complex-works/<?php echo $chapter['uri'];?>"><?php echo $chapter['name_' . $this->lang] . ' (' . $chapter['post_count'] . ')'; ?></a></li>
							<?php endforeach;?>
						</ul>
					</div>
				</td>
			</tr>
		</table>
	</div>
	<div id="footer">
	</div>
</div>
</body>