<body>
<div id="wrapper">

	<div id="header">
			<div id="logo" style="width: 250px;">
					<a href="/admin"><div id="u"></div><br/>Адміністративна панель<br/>Об'єднані бізнес-лабораторії</a>
			</div>
			<div id="upMenu">
					<a href="/admin/pages">Сторінки</a>
					<a href="/admin/portfolio">Портфоліо</a>
					<a href="/admin/blog">Блог</a>
					<a href="/admin/labs">Лабораторії</a>
					<a href="/admin/logout">Вийти</a>
			</div>
	</div>
	
	<div id="footer">
	</div>
</div>
</body>