<body>
    <?php //echo $this->partial('partials/feedback.phtml'); ?>
<div id="wrapper">

	<?php 
            echo $this->partial('partials/header.phtml', 
                          array( 'lang' => $this->lang , 
                                 'constants' => $this->constants,
                                 'uri' => $this->uri));  
	?>
	<div id="content">
		<a href="/<?php echo ($this->lang == 'ua' ? '' : $this->lang . '/'); ?>" id="back"><?php echo $this->constants['back_to_home_' . $this->lang][0]; ?></a> 
		<br/>
		<br/>
		<div id="blogHeader"><?php echo $this->constants['blog_title_' . $this->lang][0]; ?></div>
		<br/>
		
		<div id="search">
			<form id="search_form" action="/<?php echo ($this->lang == 'ua' ? '' : $this->lang . '/'); ?>blog/search/" method="post" >
				<div id="searchInput">
					<input id="searchInputField" name="search_query" type="text" value="<?php echo $this->constants['search_' . $this->lang][0]; ?>"/>
					<input id="default_searchInputField" type="hidden" value="<?php echo $this->constants['search_' . $this->lang][0]; ?>"/>
				</div>
				<div id="button"><?php echo $this->constants['find_' . $this->lang][0]; ?></div>
			</form>
			<div id="singUp">
				<a href=""><img src="/img/portfolio_rss_16.jpg"/></a>
				<a href=""><img src="/img/portfolio_vk_16.jpg"/></a>
			</div>
		</div>
		
		<div id="posts">
			<div class="post">
				<div class="date">
					<span class="day"><?php echo (int)$this->post['date']['day'];?></span><br/>
					<span class="month"><?php echo $this->post['date']['month'];?> <?php echo $this->post['date']['year'];?></span>
				</div>
				<div class="countComments"><?php echo $this->post['comment_count'];?></div>
				<div class="title">
					<a href="/<?php echo ($this->lang == 'ua' ? '' : $this->lang . '/'); ?>blog/post/<?php echo $this->post['uri'];?>"><?php echo $this->post['title_' . $this->lang];?></a>
				</div>
				<div class="postInfo"><?php echo $this->constants['author_' . $this->lang][0]; ?>: 
						<?php 
							$authors = '';
							foreach($this->post['authors'] as $author){
								$authors .= $author['name_' . $this->lang] . ', ';
							}
						?>
						<span class="author">
							<?php echo substr($authors, 0, strlen($authors) - 2) . ' '; ?>
						</span> 
						<?php 
							$labels = '';
							foreach($this->post['labels'] as $label){
								$labels .= $label['name_' . $this->lang] . ', ';
							}
						?> 
						<span class="labels">
							<?php echo substr($labels, 0, strlen($labels) - 2) . ' '; ?>
						</span>
				</div>
				<a href="/<?php echo ($this->lang == 'ua' ? '' : $this->lang . '/'); ?>blog/post/<?php echo $this->post['uri'];?>"><img src="/img/posts/<?php echo $this->post['uri']?>/<?php echo $this->post['title_img']?>" class="postImg"/></a>
				<div class="description">
					<?php echo $this->post['text_' . $this->lang];?>
				</div>
				<br/>
				<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4e3a3f4012e1eea5"></script>
				<script type="text/javascript" src="https://apis.google.com/js/plusone.js">{lang: 'uk'}</script>
				<script type="text/javascript" src="http://userapi.com/js/api/openapi.js?33"></script> 
				<script type="text/javascript">VK.init({apiId: 2430229, onlyWidgets: true});</script>
				<div id="socialButtons">
					<table cellpadding="0" cellspacing="0" border="0"> 
						<tr valign="top"> 
							<td style="width:78px;"> 
								<a class="addthis_button_google_plusone" g:plusone:size="medium" style="position:relative;  display:inline-block;width: 78px;" /> 
							</td>
							<td> 
								<a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="uBusinessMan">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
							</td> 
							<td style="padding-right:0!important">
								<div id="vk_like"></div><script type="text/javascript">
								VK.Widgets.Like("vk_like", {type: "mini", verb: 1, width: "97"}, '');
								 function helloWorld(plusone) { window.alert('+1 Triggered, State=' + plusone.state);}
								</script>
							</td> 
							<td> 
								<div style="width:79px;overflow:hidden;padding-right: 25px;"> 
									<a class="addthis_button_facebook_like" fb:like:width="95" fb:like:locale="en_US"></a> 
								</div> 
							</td> 
						</tr> 
					</table> 
				</div>
				<br/>
				<div class="comments">
					<?php foreach($this->comments as $comment): ?>
					<div class="comment">
						<?php echo $comment['author']; ?><br/>
						<?php echo $comment['email']; ?><br/>
						<?php echo $comment['text']; ?><br/>
					</div>
					<br/>
					<?php endforeach;?>
				</div>
			</div>
			<br/>
		</div>
		<div id="rightMenu">
			<div id="rightMenuHeader"><?php echo $this->constants['chapters_title_' . $this->lang][0]; ?>:</div>
			<br/>
			<ul class="menu">
				<?php foreach($this->generalChapters as $chapter):?>
					<li><a href="/<?php echo ($this->lang == 'ua' ? '' : $this->lang . '/'); ?>blog/chapter/<?php echo $chapter['uri'];?>"><?php echo $chapter['name_' . $this->lang] . ' (' . $chapter['post_count'] . ')'; ?></a></li>
				<?php endforeach;?>
			</ul>
			<br/>
			<ul class="labMenu">
				<?php foreach($this->labChapters as $chapter):?>
					<li class="<?php echo strtolower($chapter['lab']); ?>"><a href="/<?php echo ($this->lang == 'ua' ? '' : $this->lang . '/'); ?>blog/chapter/<?php echo $chapter['uri'];?>"><?php echo $chapter['name_' . $this->lang] . ' (' . $chapter['post_count'] . ')'; ?></a></li>
				<?php endforeach;?>
			</ul>
		</div>
	
	</div>
	
	<div id="footer">
	</div>
</div>
</body>